gui:
  nerdFontVersion: "3"

customCommands:
  - key: "b"
    command: "git branch --merged | grep -Ev '\\*|develop|main|master|release' | xargs -r git branch -d"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "prune local branches that have been merged to master"
  - key: "b"
    command: "tig blame -- {{.SelectedFile.Name}}"
    context: "files"
    description: "blame file at tree"
    subprocess: yes
  - key: "b"
    command: "tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: "commitFiles"
    description: "blame file at revision"
    subprocess: yes
  - key: "B"
    command: "tig blame -- {{.SelectedCommitFile.Name}}"
    context: "commitFiles"
    description: "blame file at tree"
    subprocess: yes
